[package]
name = "wasm-game-of-life-bhaveshnarra"
version = "0.1.0"
authors = ["bhaveshnarra <bhaveshsunny60@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
js-sys = "0.3"
fixedbitset = "0.3.0"